### ISSUE TITLE
Hidden Hotkeys?

### ISSUE THREAD

**Issue by byseeing** [timuric/Content-generator-sketch-plugin#101]
Hey there, I believe your plugin is conflicting with Sketch Measure for certain hotkeys. Specifically, Control+Shift+3. But these hotkeys aren't documented anywhere, or listed in the plugin's menu.
EDIT: Never mind, it's Invision's new plugin. Sorry to trouble you! Love your plugin.

**Comment by timuric** [comment]
Good to know that :)
