### ISSUE TITLE
Content Generator for Sketch - Doesn't fill shapes with images

### ISSUE THREAD

**Issue by usaps** [timuric/Content-generator-sketch-plugin#112]
08/03/16 19:16:18,475 Sketch[55200]: Exception: TypeError: fill.setPatternImage_collection_ is not a function. (In 'fill.setPatternImage_collection_( image  ,coll)', 'fill.setPatternImage_collection_' is undefined)
08/03/16 19:16:18,475 Nature and urban (Sketch Plugin)[55200]: TypeError: fill.setPatternImage_collection_ is not a function. (In 'fill.setPatternImage_collection_( image  ,coll)', 'fill.setPatternImage_collection_' is undefined)
line: 145
sourceURL: /Users/Triton/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Content Generator Sketch Plugin/Photos/Nature and urban.sketchplugin
column: 50

**Comment by timuric** [comment]
Looks like you are using old version of the plugin

**Comment by usaps** [comment]
Now works, Thanks!

BTW it’s not so easy to keep track of the plugins version, but i’ll keep in mind to reinstall them from time to time

👍
