### ISSUE TITLE
[Question] I have seen russian names in data, but how can i use it in generator?

### ISSUE THREAD

**Issue by ru-web-designer** [timuric/Content-generator-sketch-plugin#113]
When i generate persona names, plugin generates latin names. I have seen russian, cyrillic-written names in names arrays in data, but how can i activate them for using in generating proces?

**Comment by timuric** [comment]
You can extend the plugin by creating (or modifying existing) new data sets in the Data folder. Simply explore what is under the hood of sketch plugins. It is a good idea to use a [code editor](https://atom.io/) though (default textEdit can brake things).

**Comment by timuric** [comment]
Also you might want to look into this plugin http://www.invisionapp.com/craft Which allows to extend the datasets easily. In the future I plan to retire this plugin, since I expect majority of users would migrate to Craft.
