### ISSUE TITLE
Persona photos not working

### ISSUE THREAD

**Issue by Ryan529** [timuric/Content-generator-sketch-plugin#119]
For some reason, "Rad Faces" is the only image I am able to see. Neither male, female, or Neutral Persona images work. It used to, and I do have the latest version, so I'm not sure what's up.

**Comment by timuric** [comment]
@Ryan529 Are you using the latest version of the plugin? And latest sketch version?

**Comment by Ryan529** [comment]
Yes to both.

Ryan Anderson
206.547.0954

**Comment by LucienLee** [comment]
Same Issue. Here is error from console.
<img width="1037" alt="2016-05-09 01 30 18" src="https://cloud.githubusercontent.com/assets/1758453/15099357/dadbd640-1585-11e6-99cd-3125cfe53198.png">

**Comment by timuric** [comment]
@Ryan529 @LucienLee Guys I believe you are using sketch toolbox to update the plugin (which doesn't actually work) thus you are using the older version of the plugin. Please do a manual update of the plugin

**Comment by Ryan529** [comment]
In my case I manually updated it, but I can check versions again.

Ryan Anderson
206.547.0954

**Comment by LucienLee** [comment]
Indeed, after I manually installed from github, it works.
However, why it happened? Sketch toolbox pulls the repo from github, so it's supposed to be the newest version when I installed from Sketch toolbox every time, isn't it?

**Comment by timuric** [comment]
Sketch toolbox is quite buggy, and as far as I know is not really maintained :)

**Comment by Ryan529** [comment]
Cool, seems to be working again. Ditched toolbox and grabbed the latest 
download. 

Thanks so much!

On Thu, May 12, 2016 at 7:37 AM, Ryan Anderson <ryan.anderson529@gmail.com> 
wrote:

> In my case I manually updated it, but I can check versions again. 
>
> Ryan Anderson
> 206.547.0954
> On May 12, 2016 1:55 AM, "Timur Carpeev" <notifications@github.com> wrote:
>
>> @Ryan529 <https://github.com/Ryan529> @LucienLee 
>> <https://github.com/LucienLee> Guys I believe you are using sketch 
>> toolbox to update the plugin (which doesn't actually work) thus you are 
>> using the older version of the plugin. Please do a manual update of the 
>> plugin
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/timuric/Content-generator-sketch-plugin/issues/119#issuecomment-218698310>
>>
>


-- 
Ryan Anderson
C: 206.547.0954
