### ISSUE TITLE
Sketch 3.9.1 (or 39.1?) Breaks the Content Generator Plugin

### ISSUE THREAD

**Issue by nwisnia** [timuric/Content-generator-sketch-plugin#127]
Looks like the Content Generator will not work with this latest Sketch version release.

**Comment by romanr** [comment]
How did you get it working?

**Comment by nwisnia** [comment]
@Romanr It's been a hot minute but I think just a simple uninstall and reinstall of the plugin solved my problem sorry I didn't see your message sooner my alerts were turned off and I'm not currently a regular contributor/user:(
