### ISSUE TITLE
Generated persona avatars are not diverse

### ISSUE THREAD

**Issue by chanpory** [timuric/Content-generator-sketch-plugin#128]
Please add more people of color when generating avatars for personas.

**Comment by timuric** [comment]
@chapory pictures are selected using a range sample from http://uifaces.com 
I agree that was not the best way to sample, but it was quick and easy.
Please feel free to add more diversity to the sample!

**Comment by sogen** [comment]
it seems uifaces doesn't exist.
@chanpory you can add more to the data/images/persona/ folder
