### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by bomberstudios** [timuric/Content-generator-sketch-plugin#130]
Hi there,

As you probably know, `setPatternImage:` has been deprecated for a while, and it will be removed in Sketch v40. Please update your Plugin to use `setImage:` instead or it won't work in the next release :)

**Comment by timuric** [comment]
@bomberstudios I just tried ```setImage``` in Sketch 39.1 and it crashes :/

**Comment by sogen** [comment]
in v40b3 a pattern appears when assigning images

**Comment by bomberstudios** [comment]
Check the comment I made in https://github.com/ScottSavarie/Clipboard-Fill/issues/4#issuecomment-247281946

**Comment by sogen** [comment]
Hi, opened PR with the changes
