### ISSUE TITLE
It doesn't work on V.40

### ISSUE THREAD

**Issue by misterfulanito** [timuric/Content-generator-sketch-plugin#136]
Sketch is just updated to v.40 and the plugin has been depreciated so, could you update this awesome plugin for us, please? Thank you.

**Comment by Oasisontheplains** [comment]
pretty please...

**Comment by ridder-mark** [comment]
plz...

**Comment by o1gac** [comment]
Same here... please :)

**Comment by saltnpixels** [comment]
+1

**Comment by edgarve** [comment]
+1

**Comment by ChrissyChien** [comment]
Same.....

**Comment by timuric** [comment]
Hold on there guys, almost done

**Comment by timuric** [comment]
Could you guys please give it a spin before I push it to the release branch? Please donwload it from the development branch https://github.com/timuric/Content-generator-sketch-plugin/tree/development

**Comment by o1gac** [comment]
Didn't worked for me. Could install plugin successfully but dummy data like photo etc. not appeared on workspace.

**Comment by timuric** [comment]
@o1gac I just tested it with Version 40 (33762) and it works. Please try to remove everything CG related and try to install again

**Comment by timuric** [comment]
@o1gac perhaps that was an issue related to the fill type. Please try downloading once again, I just pushed a fix to development branch ;)

**Comment by misterfulanito** [comment]
@timuric It works but in the menu we can find the plugin into Legacy Plugins (deprecated) as you can see in the image.

👇

![captura de pantalla 2016-09-22 a las 8 11 39 a m](https://cloud.githubusercontent.com/assets/813025/18749430/6fe32f82-809c-11e6-870c-ac58082c498d.png)

Thank you, man.

**Comment by timuric** [comment]
@misterfulanito You had to use development version. But anyways, I just released a new version. Please remove the old one and download the new one ;)

**Comment by o1gac** [comment]
Thank you :) Keep up the good work.

**Comment by ridder-mark** [comment]
You da man
