### ISSUE TITLE
Do you plan to update your plugin for Sketch 40?

### ISSUE THREAD

**Issue by edge0703** [timuric/Content-generator-sketch-plugin#138]
I want to mention it in The Sketch Handbook (http://www.sketch-handbook.com/), but only if it works with the current version of Sketch.

**Comment by timuric** [comment]
@edge0703 its already working with v40 for quite some time, are you using the latest version?

**Comment by edge0703** [comment]
Yeah, realized that I need to un- and reinstall it. Now it works, thanks for your quick help!

**Comment by timuric** [comment]
@edge0703 note that if you are using sketch toolbox, updates can be buggy ;)

**Comment by edge0703** [comment]
Looks like.
