### ISSUE TITLE
Inserting persona photo's does not work

### ISSUE THREAD

**Issue by anketwokings** [timuric/Content-generator-sketch-plugin#139]
First of all, thank you for this cool plugin, great work. 
I cannot get the persona photos to work, probably something to do with the latest sketch version or so. The normal 'images' _are_ working, just not the persona ones.

**Reproduce:**
Click: Persona > Photos > Female . (Or male or Neutral)

**I expect**
That my rectangles will be filled with persona images.

**What happens:**
Nothing

**Console log:**
```
03/10/16 14:06:41,926 Female (Sketch Plugin)[401]: TypeError: null is not an object (evaluating 'imagesFileNames. count')
line: 153
sourceURL: /Users/anke/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Content Generator Sketch Plugin/CG.sketchplugin/Contents/Sketch/Persona/Photos/Female.js
column: 35
```

**Sketch version:**
Version 40.1 (33804)

Have a good day!

**Comment by timuric** [comment]
@anketwokings perhaps you are using old plugin. Please update it manually (sketch toolbox might not work properly)

**Comment by anketwokings** [comment]
Thank you; Indeed, the Sketch Toolbox version is not up to date. 
I reinstalled the zip version from github and all seems to be working fine.

Keep up the good work!
