### ISSUE TITLE
Plugin doesn't update text until I restart Sketch

### ISSUE THREAD

**Issue by sawtoothwave** [timuric/Content-generator-sketch-plugin#140]
Hey there-

Sorry if this is a known issue; I'm fairly new to both Github AND Sketch. When I use the plugin it appears as if it's done nothing, but if I save the document, close Sketch, restart the app, and reload the document, there's generated text in my paragraph after all.

I've attached a screenshot of my console from the last few times I tried to run the plug. I'm running the newest version of Sketch (as of now), version 40.1

<img width="1662" alt="screen shot 2016-10-04 at 10 05 34 pm" src="https://cloud.githubusercontent.com/assets/7399341/19098841/bd75d394-8a7e-11e6-9d7a-3624b2f04ba9.png">

Thank you!!
-Mike

**Comment by timuric** [comment]
Looks like you are using outdated version of the plugin. Please update manually
