### ISSUE TITLE
Custom string not available, Sketch Version 40.1 (33804), macOS Sierra 10.12

### ISSUE THREAD

**Issue by paulvantuyl** [timuric/Content-generator-sketch-plugin#141]
I'm no longer able to access the custom string (probably my most used feature).

![grab](https://cloud.githubusercontent.com/assets/1455047/19162820/49e09d70-8bae-11e6-865e-8d41f3365568.jpg)

**Comment by timuric** [comment]
Thanks for reporting, its fixed now, please update!
