### ISSUE TITLE
"Persona>Photos" does not work

### ISSUE THREAD

**Issue by yooooka** [timuric/Content-generator-sketch-plugin#142]
Here is the console error. Could you take a look at it?

_10/24/16 11:59:22.685 AM Neutral (Sketch Plugin)[1435]: TypeError: null is not an object (evaluating 'imagesFileNames. count')
line: 153
sourceURL: /Users/---/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Content Generator Sketch Plugin/CG.sketchplugin/Contents/Sketch/Persona/Photos/Neutral.js
column: 35_

**Comment by adrianspeaking** [comment]
This is not working for me either. Male, Female or Neutral, all of them do nothing when selected.

**Comment by trai25** [comment]
I got the problem too.

**Comment by timuric** [comment]
You are using old plugin. Please update
