### ISSUE TITLE
Issue with content generator plugin

### ISSUE THREAD

**Issue by donnguyendev** [timuric/Content-generator-sketch-plugin#144]
I'm sorry for bothering you, but there seems to be a bug with the content generator. I haven't got a chance to try the plugin due to it not working at all. Here is some information from the console, hopefully you can solve this. Thanks. 

I'm running version 3.8.1 of Sketch by the way.

12/6/16 5:23:38.979 AM Male (Sketch Plugin)[12511]: TypeError: null is not an object (evaluating 'imagesFileNames. count')
line: 153
sourceURL: /Users/macbook/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Content Generator Sketch Plugin/CG.sketchplugin/Contents/Sketch/Persona/Photos/Male.js
column: 35
stack: getImageCollection@/Users/macbook/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Content Generator Sketch Plugin/CG.sketchplugin/Contents/Sketch/Persona/Photos/Male.js:153:35
main@/Users/macbook/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Content Generator Sketch Plugin/CG.sketchplugin/Contents/Sketch/Persona/Photos/Male.js:191:41
loadImages@/Users/macbook/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Content Generator Sketch Plugin/CG.sketchplugin/Contents/Sketch/Persona/Photos/Male.js:209:6
onRun@/Users/macbook/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Content Generator Sketch Plugin/CG.sketchplugin/Contents/Sketch/Persona/Photos/Male.js:214:15

**Comment by rockallite** [comment]
Follow the [official instructions](https://github.com/timuric/Content-generator-sketch-plugin#installation) to install the plugin.

Don't use Sketch Toolbox to install the plugin. It won't work that way. I've tried.
