### ISSUE TITLE
Inserting text block?

### ISSUE THREAD

**Issue by paaljoachim** [timuric/Content-generator-sketch-plugin#150]
Hey

I have a text section and went to insert lorum ipsum text but nothing happend.
I have tried it in various ways but to me it looks like it is not working with the newest version of Sketch.

**Comment by ChrisARaymond** [comment]
I have the same problem, using Sketch 41.2.

**Comment by norhes** [comment]
I have the same issue as well, using Sketch 41.2

**Comment by guizput** [comment]
Hey everyone! I just found out in another topic how to get this working.
You cannot use the text generator if your text is actually active. Try hitting the ESC key to make sure the text you are targeting is not active and generate the lorem again. It works for me.

**Comment by ChrisARaymond** [comment]
@guizput That works! Thanks for the tip!
