### ISSUE TITLE
Crash in Sketch 42

### ISSUE THREAD

**Issue by bomberstudios** [timuric/Content-generator-sketch-plugin#151]
Hi there,

in Sketch 42, we've removed an exception we used to have for `NSAppTransportSecurity`, so now you're only allowed to load remote content over HTTPS. The Rad Faces feature tries to load content over HTTP, and that's crashing Sketch 42.

You may want to look for an alternative URL for that JSON that uses HTTPS.

Hope it helps!

**Comment by misterfulanito** [comment]
Is the same with Persona > Female, Male or Neutral ? Because I can't load any data from it.

**Comment by jaminroe** [comment]
I miss Rad Faces 😢  You could use InVision's Craft plug-in, and navigate to the faces from there using their Web tab

**Comment by jaminroe** [comment]
So that doesn't even work now, since Craft recognizes it's not via HTTPS. I found a solution though, I used the Custom tab in Craft, and made my own collection using local files:

![image](https://cloud.githubusercontent.com/assets/1559447/22994722/00273f72-f396-11e6-8537-12c3be9a4894.png)
