### ISSUE TITLE
Image can't show~

### ISSUE THREAD

**Issue by ycjcl868** [timuric/Content-generator-sketch-plugin#152]
![image](https://cloud.githubusercontent.com/assets/13595509/22627279/38211f80-ebfb-11e6-9171-50bfb33bbb32.png)

**Comment by sureshmurali** [comment]
Yeah.. its not working for me too.
OS 10.12.3

**Comment by jayechau** [comment]
e...persona's photos can not display  too
OS  10.12.2

**Comment by dantejauregui** [comment]
yeah not working here too :(

**Comment by skondris** [comment]
This broke with sketch 42 because of the change in how sketch now requires secure https:// calls only. the uifaces.com resource that the persona>photos>... option calls is not a secure URL :( we need to get the dev behind uifaces.com to add a cert so his site can be called via https://

**Comment by edubasabe** [comment]
So sad :(

**Comment by timuric** [comment]
Personas are working, simply update the plugin.

**Comment by skondris** [comment]
I had the plugin from Feb, I deleted it, downloaded the new one from Mar, but I still do not get any images from the Persona>Photos options,...

**Comment by edubasabe** [comment]
@timuric Still not working :(

**Comment by Gilmantas** [comment]
Same here...

**Comment by timuric** [comment]
Which version of of sketch you are using? Did you updated the plugin manually or used sketch toolbox? I just tested it, and it works with sketch 42 (36781)

**Comment by skondris** [comment]
Sketch 42 (36781) and I have not used toolbox for a while now (months).  I closed Sketch, moved the old content generator plugin folder to my trash, downloaded the new one (dated March 6, 2017) and unzipped it, and then dropped the entire 'Content-generator-sketch-plugin-master 2' folder into my sketch plugins folder. 

I restarted sketch, and it won't work for me.

**Comment by Gilmantas** [comment]
Tried to reinstall manually (without using the Sketch toolbox) and it started to work! Thanks @timuric !

**Comment by skondris** [comment]
What am I doing wrong then? :/

**Comment by timuric** [comment]
@skondris delete everything you have, download the archive, double click on CG.sketchplugin to install it again. See if it helps

**Comment by skondris** [comment]
That worked! I hadn't realized I needed to double-click the CG.sketchplugin file to install it, I had just been dropping it in the plugins folder. 

thank you so much!!!

**Comment by timuric** [comment]
@skondris You are welcome!

**Comment by edubasabe** [comment]
It works, thank you @timuric !

**Comment by vincentw3** [comment]
Still not working :( 
this broke with sketch 44.1(41455)

**Comment by timuric** [comment]
@vincentw3 please update manually

**Comment by vincentw3** [comment]
@timuric  Still not working :(
