### ISSUE TITLE
[Docs] Please Add Instructions on How to Install via Sketch Plugin Manager

### ISSUE THREAD

**Issue by luxlogica** [timuric/Content-generator-sketch-plugin#155]
The **[Sketch Plugin Manager](https://mludowise.github.io/Sketch-Plugin-Manager/)** is an amazing project, combining the best of all plugin managers that came before it:

* it is a normal Sketch plugin, that works inside Sketch's own 'Plugins' menu - i.e., it is not a separate app, and does not instal obtrusive menu items in your menubar.
* it provides a beautiful, searchable, easy-to-use interface for users to find the plugins they need.
* it automatically instals plugins listed in Sketch's official plugin directory, straight from the plugin's GitHub repo, requiring **no configuration** or special setup at all from the developer.
* it automatically advises users when a plugin needs updating, and updates them automatically with a single click.
* it provides the user with an easy-to-find, clickable link to your plugin homepage/GitHub repo.
* it can uninstall plugins with a single click, too.

The instructions that your users would need in order to instal Content Generator via [Sketch Plugin Manager](https://mludowise.github.io/Sketch-Plugin-Manager/) are:

``` markdown
Installation via [Sketch Plugin Manager](https://mludowise.github.io/Sketch-Plugin-Manager/):

1. In the 'Catalog' tab of the Sketch Plugin Manager window, click in the 'Search' field and type 'Content Generator', to filter the list.
2. You will see the 'Content Generator' plugin listed at the top of the list. Click the 'Instal' button inside it.
```

Adding these instructions would greatly help popularise and support the project.

**Comment by timuric** [comment]
Thank you @luxlogica!
