### ISSUE TITLE
TypeError: null is not an object (evaluating 'imagesFileNames. count')

### ISSUE THREAD

**Issue by DaBlackBeerd** [timuric/Content-generator-sketch-plugin#156]
Sketch (version 44.1) crashing when attempting to generate any kind of persona.
Getting this error in the console:

5/31/17 4:15:06.980 PM Male (Sketch)[11960]: TypeError: null is not an object (evaluating 'imagesFileNames. count')
line: 153
sourceURL: /Users/jacobcarpenter/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Content Generator Sketch Plugin/CG.sketchplugin/Contents/Sketch/Persona/Photos/Male.js
column: 35
stack: getImageCollection@/Users/jacobcarpenter/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Content Generator Sketch Plugin/CG.sketchplugin/Contents/Sketch/Persona/Photos/Male.js:153:35
main@/Users/jacobcarpenter/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Content Generator Sketch Plugin/CG.sketchplugin/Contents/Sketch/Persona/Photos/Male.js:191:41
loadImages@/Users/jacobcarpenter/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Content Generator Sketch Plugin/CG.sketchplugin/Contents/Sketch/Persona/Photos/Male.js:209:6
onRun@/Users/jacobcarpenter/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Content Generator Sketch Plugin/CG.sketchplugin/Contents/Sketch/Persona/Photos/Male.js:214:15

**Comment by timuric** [comment]
please update manually
