### ISSUE TITLE
Persona / Photo / Male-Female not working

### ISSUE THREAD

**Issue by justdan0227** [timuric/Content-generator-sketch-plugin#161]
For some reason I can't get the Persona option to work.  I can get Flickr data to work but not images from Persona.  Thoughts?

**Comment by markwadedotnet** [comment]
I'm having the same issue.

**Comment by EdsonAlcala** [comment]
+1

**Comment by jhonathas** [comment]
+1

**Comment by jhonathas** [comment]
I installed using the Runner plugin, and it went live.

**Comment by timuric** [comment]
please update manually
