### ISSUE TITLE
Sketch plugin updater does not work

### ISSUE THREAD

**Issue by bomberstudios** [timuric/Content-generator-sketch-plugin#162]
Looks like the update from Sketch enters an infinite loop, because the appcast says there's a v1.1 available, but the version on your `manifest.json` is 1.0. So Sketch downloads the "update" and doesn't install it (its version is not higher than the currently installed 1.0) and the Update button does nothing.

Bumping the version on manifest.json to 1.1 should fix it.

**Comment by timuric** [comment]
Thanks, just did that 
https://github.com/timuric/Content-generator-sketch-plugin/commit/5ccbbfb37a02a6bcf9144b466257e0ddd1d7387e
