### ISSUE TITLE
Images Not Working

### ISSUE THREAD

**Issue by ohyoda** [timuric/Content-generator-sketch-plugin#186]
Hello! I'm new to learning Sketch and I'm very excited about this plug-in, however I can't seem to get the Persona images or Instagram images to work (weirdly flickr images work okay). I don't receive any kind of error code I just don't get anything displaying. I have installed normally and through Sketch Plug-in Manager. I also saw something about renaming the folder to "Generator" and that hasn't worked for me either. I'm on Sketch 53.1 and using the most up to date version of Content Generator. Any help would be very much appreciated!

**Comment by timuric** [comment]
Sketch can generate data now natively. Check it out in preference panel ;)
