### ISSUE TITLE
Images disappear when quitting and reopening

### ISSUE THREAD

**Issue by cleercode** [timuric/Content-generator-sketch-plugin#3]
At least some of the times when I quit and reopen a file with images generated from the plugin, the images no longer show. The image layers are still there.

(Sketch 3.01 beta)

**Comment by jacobhalton** [comment]
I've seen this as a bug in Sketch in general. Are you sure it's the plugin causing the issue and not a conflict with Sketch's bug?

**Comment by andrewtennison** [comment]
2nd that. I had your plugin installed but had not used it. All my images have disappeared despite layers still being there. For some reason they are also gone from all historical versions as well.
