### ISSUE TITLE
[Question] How can I add a new folder with my own pics?

### ISSUE THREAD

**Issue by hiulit** [timuric/Content-generator-sketch-plugin#49]
I tried duplicating the existing Landscape example and renaming it with the new path but it's not working...

**Comment by timuric** [comment]
Try using simple path names, without special characters

**Comment by hiulit** [comment]
Hey, yeah, I'm using only letters, no spaces nor special characters and it doesn't seem to work. Could you give an example of how to it? Or do you need more feedback? Thanks!

**Comment by timuric** [comment]
If original plugins work, then so do yours should work. Maybe the name of the files have special characters?
