### ISSUE TITLE
Text - Dummy text

### ISSUE THREAD

**Issue by mischugo** [timuric/Content-generator-sketch-plugin#52]
Text Dummy text - create or replace - both does not work :-(

**Comment by timuric** [comment]
@mischugo works for me. Make sure you are using the latest version of the plugin

**Comment by jaminroe** [comment]
Also "partly" works for me, but most people wouldn't realize this. It seems to be broken. Look at the screenshot. It does replace/generate the text, but it doesn't update in the canvas unless you move the layer or edit it. If you hover over the layer, you can see the generated text. So I'm considering this a bug :stuck_out_tongue_winking_eye: 

![screen shot 2015-05-29 at 12 37 51 pm](https://cloud.githubusercontent.com/assets/1559447/7887565/2447ebb6-0600-11e5-925f-098159792fed.png)

**Comment by timuric** [comment]
@jaminroe could be a bug, but could be an Sketch an API issue. Would look into it in the future (sorry busy atm)

**Comment by jaminroe** [comment]
Latest version works now, very well. You may close this
