### ISSUE TITLE
[Question] Could the project have a blank text template for our own text?

### ISSUE THREAD

**Issue by joshuamauldin** [timuric/Content-generator-sketch-plugin#55]
I'm familiar with how to customize this on my own, but wonder if it may be beneficial for others to have one that's free for adding their own.

**Comment by timuric** [comment]
@joshuamauldin agree, customisation is the number one request I get. Unfortunately I am busy around the clock until the end of the summer and I don't have any time to contribute to the project. If you would like to send a pull request I would would gladly to merge it ;)

**Comment by joshuamauldin** [comment]
Great! I created one: https://github.com/timuric/Content-generator-sketch-plugin/pull/56
