### ISSUE TITLE
Custom String

### ISSUE THREAD

**Issue by ivancucer** [timuric/Content-generator-sketch-plugin#57]
Hello Timur,

Thank you very much for such an amazing plugin. It helps me a lot. But I noticed an issue or limitation. So I'm writing about "Custom String". For example, I have this string
```javascript
[1-600] [Arthur Avenue,Broadway], New York, NY [10001-11692]
```
which has two streets **Arthur Avenue, Broadway**. Yes, this string works like a charm. But there is an issue if I write more than 2 streets
```javascript
[1-600] [Arthur Avenue,Broadway,Dyre Avenue,East 233rd Street,Fordham Road,Grand Concourse,Gun Hill Road,Jerome Avenue,Metropolitan Avenue,Mosholu Parkway,New York State Route 9X,Park Avenue,Pelham Parkway,Sedgwick Avenue,Southern Boulevard,Third Avenue,Webster Avenue,White Plains Road], New York, NY [10001-11692]
```

Take a look at this video: http://take.ms/dJxhC

If you have a chance please fix this amazing plugin :+1: 

Thanks in advance!

Best!
Ivan

**Comment by pkvdesigns** [comment]
+1 on this. Use the plugin a lot and this would make it even beter!

**Comment by timuric** [comment]
@ivancucer @pkvdesigns Hey, I rewrote the plugin. Please give it a spin and let me know if you find bugs.

**Comment by ivancucer** [comment]
@timuric thanks a lot! But there are few issues. Unfortunately the new update loses commas ```  ,  ``` spaces and other parts from the brackets etc... eg. New York or NY etc...

![untitled sketch 2015-06-10 1 am-03-09](https://cloud.githubusercontent.com/assets/2349195/8071657/7fc52fc0-0f0c-11e5-9aa2-7263b694fdee.jpg)

**Comment by pkvdesigns** [comment]
Thanks getting there! Also comma's used as text inbetween are removed.
E.g.: $[0-20],[00-99] [new,old,used]

Should result in $16,06 used but now I would get $166 used.

**Comment by timuric** [comment]
@ivancucer @pkvdesigns thanks for testing. Please try it again, hopefully no bugs this time :)

**Comment by pkvdesigns** [comment]
@timuric works like charm, thanks a bunch.

I would make it even more versatile if the divider in those brackets is something that isn't used in a text (a ~ for instance) instead of the comma. E.g. [1234EG, Weesp~5431GA, Amsterdam].

Really a nice to have, I understand that the current way is easier as an array.

**Comment by ivancucer** [comment]
Perfect! Thank you!
@pkvdesigns yeah, nice idea.

**Comment by timuric** [comment]
@pkvdesigns Lets make a trade, I would add this feature in exchange of Custom String instruction/tutorial for the README file :D

**Comment by pkvdesigns** [comment]
@timuric here you go ;) :

**Custom strings**
![custom string](https://cloud.githubusercontent.com/assets/5709624/8092928/c18d6d76-0fbd-11e5-962d-417165cc1a2d.gif)

You can create a custom string by combining any of these options:
- plain text (example: banana)
- random number from range (example: [0-20] )
- random item from an array (example: [new,used,old] )

An example of a combined string: $[0-999],[10-99] [new,used,old]
Which would result in "$321,34 old" or "$12,75 new"

**Comment by timuric** [comment]
@pkvdesigns Damn you are fast :D 
Thanks a lot, I would add it to the main page, and replace comma with ~ ;)
Let me know if you have more ideas for improvements.

**Comment by ivancucer** [comment]
@pkvdesigns really fast!! thanks! @timuric can't wait!!!

**Comment by pkvdesigns** [comment]
@timuric no problem, least I can do ;) can you give me a heads up here when the update is online. Thanks for all the work, its an awesome plugin.

**Comment by timuric** [comment]
@pkvdesigns Thanks, its live!

**Comment by ivancucer** [comment]
:+1:

**Comment by ivancucer** [comment]
One more thing :) What do you think about this string with dots and commas: [6.253,34-17.328,98] ?

**Comment by ivancucer** [comment]
Any comments ? :)

**Comment by ivancucer** [comment]
Ah we lost this feature in the latest update :(

**Comment by ivancucer** [comment]
sorry my bad. I made a mistake :)

**Comment by ivancucer** [comment]
so what about string with dots and commas: [6.253,34-17.328,98] ? :)

**Comment by ivancucer** [comment]
Hey, any news ? :) I guess, you didn't see my comments because this ticket is closed. I'll create a new ticket :)

**Comment by timuric** [comment]
@ivancucer sorry I have quite bussy time now. Would keep this in mind as soon as would have time to work on updates
