### ISSUE TITLE
Remove Inappropriate Images

### ISSUE THREAD

**Issue by damenleeturks** [timuric/Content-generator-sketch-plugin#61]
You're probably going to want to remove a couple images of a guy grabbing his crotch. 

- https://github.com/timuric/Content-generator-sketch-plugin/blob/master/data/photos/Human/1617.jpg
- https://github.com/timuric/Content-generator-sketch-plugin/blob/master/data/photos/persona/men/1617.jpg

**Comment by timuric** [comment]
@damenleeturks LOL :D Thanks for the tip!

**Comment by damenleeturks** [comment]
No problem. :)
