### ISSUE TITLE
How do I use the Geo tool?

### ISSUE THREAD

**Issue by dodchris** [timuric/Content-generator-sketch-plugin#72]
I don't understand how to use the geo tool. Is it supposed to import a map into my design?

The way I've tried using it is like the photos tool;
Draw a shape -> Select shape -> Choose City/Region -> Nothing happens

**Comment by auxdesigner** [comment]
It generates geo-related **text**. Here is a demo GIF: https://www.dropbox.com/s/lpxf0ucs0wnqnf2/geo.gif?dl=0

**Comment by dodchris** [comment]
Gotcha. Thanks
