### ISSUE TITLE
Problem with Dummy Text (sketch 3)

### ISSUE THREAD

**Issue by dodchris** [timuric/Content-generator-sketch-plugin#73]
I can't seem to make My text to work. I have this in my-text.js:

```
data = [
"Foxton, Worcestershire",
"Wallis, Wiltshire",
"Reiss, Lincolnshire",
"Topshop, Suffolk"
];
```

I select my text objects then choose Text > Dummy Text > My Text > Generate
Nothing happens. Same with replace.

The other text generate options are working. But replace does not seem to do anything for me for any of the text options (how should that work?)

I've tried restarting the app to no avail. Have I missed a step?

**Comment by timuric** [comment]
@dodchris Make sure you are using a code editor when editing custom text (avoid TextEdit)

**Comment by dodchris** [comment]
I used sublime. Sorry, it doesn't work for me

**Comment by stabyadad** [comment]
Hello!

 

New message, please read <http://heoconshop.vn/party.php?tlta>

 

raymond@armadadigital.com

**Comment by stabyadad** [comment]
Hi,

I've just read some interesting news about our friend, just look at him, he is a star! Please read here <http://sleslykushu.intrepidbakers.com/aekdgcad>

Looking forward, raymond@armadadigital.com
