### ISSUE TITLE
Problem with USA Address

### ISSUE THREAD

**Issue by cnotte** [timuric/Content-generator-sketch-plugin#75]
When I use this options the information comes in somewhat backwards. Below is what displays" 

City: Cotati State: SC Street: Toban 955 Zip: 74168-6613

The standard US address format should display as:
Street: 955 Toban  City: Cotati   State: SC   Zip: 74168-6613

**Comment by timuric** [comment]
I would gladly accept pull request on this issue

**Comment by Gidgidonihah** [comment]
A pull request has been offered.
