### ISSUE TITLE
Adding or renaming new Images directory doesn't work

### ISSUE THREAD

**Issue by sarahlafeuil** [timuric/Content-generator-sketch-plugin#77]
Hi every one !
I'm working for a movie database website, and I have modifying the pluggin to work with a collection of movie posters, stars photos and tv shows...
First, I thought adding more directory would work, with duplicating the .sketpluggin file with the correct path. Failed :)
So, as my coding skills are really limited (I'm a ui designer), I tried to rename the directory.
For example, 
human.sketchplugin became Star.sketchplugin and I modified the path to have data/photos/Star
Failed too ! 

Anyone could explain me the process to have my own content/directories name?

Thank you !

**Comment by timuric** [comment]
@sarahlafeuil This is what you need https://github.com/timuric/Content-generator-sketch-plugin#adding-custom-images

**Comment by sarahlafeuil** [comment]
Yep, I tried this one, but I need to have severals directories to inject the right content :
- Movies Poster
- Movie Poster  for Kids
- TV Shows
- Stars 
- Screenshots
- News images
Creating severals directories in My-photos/ isn't working either.

:)

**Comment by timuric** [comment]
Then just create copy of the My-photos (with a different name), after that copy the plugin then open it with a text editor and rename the path to the the new folder. You just have to change one line of code in the plugin https://github.com/timuric/Content-generator-sketch-plugin/blob/master/Photos/My%20Photos.sketchplugin#L4

**Comment by sarahlafeuil** [comment]
This time, it worked !
But I still have issue with the pluggin : it works once on my file, then I have to close/reopen it.
I wonder if it could come from my images. I was working perfectly with yours and before the Sketch upgrade.

Thanks again !

**Comment by timuric** [comment]
@sarahlafeuil are you using the latest version of the plugin?

**Comment by sarahlafeuil** [comment]
Yep, I've just downloaded it

**Comment by sarahlafeuil** [comment]
Sh***... I've found the problem
Same as precedent issue :
"The editor automatically changed this ' to this ‘ when I edited the file... It was driving me insane!"

Thanks :)

**Comment by timuric** [comment]
@sarahlafeuil yeah, many people had similar issue
