### ISSUE TITLE
plugin seems not working with last 3.4.1 release

### ISSUE THREAD

**Issue by shakisha** [timuric/Content-generator-sketch-plugin#78]
Simply doesn't put content, it's a strange issue, was working properly before.

Any other one having this same issue?

**Comment by timuric** [comment]
Please submit console.app log [like so](https://raw.githubusercontent.com/timuric/Content-generator-sketch-plugin/master/tutorial/console.png)

Note that Sketch app is working on Version 3.4 (15575) from the Appstore.

**Comment by timuric** [comment]
@shakisha Also works with the 3.4.1. Make sure you are using the latest version
