### ISSUE TITLE
Sketch Version 3.4 - Generator not working

### ISSUE THREAD

**Issue by netpoe** [timuric/Content-generator-sketch-plugin#79]
I recently updated to Sketch Version 3.4 and the generator plugin stopped working so I updated it as I noticed recent commits, but no success.

Nor the text, nor the images generators work anymore, which they did before the Sketch update, any ideas?

**Comment by timuric** [comment]
@netpoe it works on my machine with Sketch Appstore and Sketch Beta. Make sure you are definitely using the latest version of the plugin, and if it doesn't help then please [submit a report](https://github.com/timuric/Content-generator-sketch-plugin#feature-requests-bugs--feedback)

**Comment by angelinaho** [comment]
Hi @timuric, I also experience issues with the plugin after I upgraded to Sketch 3.4.1.

I tried to use the generator to insert some images for personas, but nothing shows up. I used the download button the main github page so I assume it's the latest version?

**Comment by timuric** [comment]
@netpoe @angelinaho In order to submit a report please do the following:

1. Open Console app Applications/Utilities/Console 
2. Type Sketch In filter box
3. Run plugin
4. Copy the contents in the Console app

**Comment by netpoe** [comment]
@angelinaho try closing and opening Sketch 3.4.1. It's working for me now with the latest plugin update. :) @timuric  thanks anyway +1:

**Comment by Lennyknowtify** [comment]
The photos aren't working on Sketch 3.5.2. Anyone else having trouble?

**Comment by Nineswiss** [comment]
Can confirm photos not working in  3.5.2 for me either.

**Comment by timuric** [comment]
Where did you guys got the 3.5.2 version? I get this message when trying to update: 
`Sketch Beta 3.5.1 is currently the newest version available.`

**Comment by jhalborg** [comment]
Automatic update for me :-) Don't even remember.

**Comment by timuric** [comment]
Guys, please use manual updates, sketchtoolbox updates are broken now
