### ISSUE TITLE
Problem with Persona > Photos

### ISSUE THREAD

**Issue by aarongilmore** [timuric/Content-generator-sketch-plugin#80]
When I try to add some user images nothing happens.

'TypeError: null is not an object (evaluating 'imagesFileNames. count')
line: 99
sourceURL: /Users/aaron/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Persona/Photos/Male.sketchplugin
column: 35'

**Comment by timuric** [comment]
@aarongilmore Maybe the plugin is pointing to a wrong path, or the path is empty?

**Comment by aarongilmore** [comment]
@timuric That was it, my bad. Fixed now.

**Comment by ianwalter** [comment]
@aarongilmore How did you fix this? I am getting the same error but the path looks right to me.

**Comment by aarongilmore** [comment]
@ianwalter It was an issue with the paths for me.
