### ISSUE TITLE
Unable to run plugin on Sketch 3.4

### ISSUE THREAD

**Issue by lmargo** [timuric/Content-generator-sketch-plugin#81]
Hi. Ever since my team updated to Sketch 3.4 we were unable to run the plugin.

The following is the response from console:

<code>
11/12/15 5:11:30.153 PM Sketch[603]: _NSExtensionIsSafeExpressionForObjectWithSubquerySubstitutions: Expression considered unsafe: SUBQUERY($extensionItem.attachments, $attachment, (NOT ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.adobe.pdf") AND (NOT ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.image"))

11/12/15 5:11:30.153 PM Sketch[603]: _NSExtensionIsSafeExpressionForObjectWithSubquerySubstitutions: Expression considered unsafe: SUBQUERY($extensionItem.attachments, $attachment, (NOT ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.adobe.pdf") AND (NOT ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.image")).@count

11/12/15 5:11:30.154 PM Sketch[603]: _NSExtensionIsSafeExpressionForObjectWithSubquerySubstitutions: Expression considered unsafe: SUBQUERY(extensionItems, $extensionItem, $extensionItem.attachments.@count == 1 AND SUBQUERY($extensionItem.attachments, $attachment, (NOT ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.adobe.pdf") AND (NOT ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.image")).@count == 0)

11/12/15 5:11:30.154 PM Sketch[603]: _NSExtensionIsSafeExpressionForObjectWithSubquerySubstitutions: Expression considered unsafe: SUBQUERY(extensionItems, $extensionItem, $extensionItem.attachments.@count == 1 AND SUBQUERY($extensionItem.attachments, $attachment, (NOT ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.adobe.pdf") AND (NOT ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.image")).@count == 0).@count

11/12/15 5:11:30.154 PM Sketch[603]: NSExtensionIsPredicateSafeToExecuteWithObject: NSPredicate considered unsafe: SUBQUERY(extensionItems, $extensionItem, $extensionItem.attachments.@count == 1 AND SUBQUERY($extensionItem.attachments, $attachment, (NOT ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.adobe.pdf") AND (NOT ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.image")).@count == 0).@count == 1

11/12/15 5:12:48.240 PM WindowServer[133]: disable_update_timeout: UI updates were forcibly disabled by application "Sketch" for over 1.00 seconds. Server has re-enabled them.

11/12/15 5:12:48.393 PM WindowServer[133]: common_reenable_update: UI updates were finally reenabled by application "Sketch" after 1.15 seconds (server forcibly re-enabled them after 1.00 seconds)
</code>

I tried uninstalling and installing the latest plugin but it doesn't seem to do it. Other plugins work just fine though, and for some reason in Sketch's plugin manager this plugin shows up as Legacy Plugin
!

[screen shot 2015-11-12 at 5 21 26 pm](https://cloud.githubusercontent.com/assets/15814788/11116007/e72e42c6-8961-11e5-85bd-9c8b716d83e3.png)

If anyone can help I'd greatly appreciate it. And thanks so much for making this plugin.

**Comment by timuric** [comment]
@lmargo are you using the latest version of the plugin?

**Comment by exterry** [comment]
@timuric I got the same issue, using Sketch 3.4.1 with latest plugin

**Comment by lmargo** [comment]
@timuric Yes, this issue still persists after I downloaded and reinstalled the latest plugin. Sometimes it works if I restart Sketch, but sometimes it doesn't work even after I restart sketch or the computer even.

**Comment by timuric** [comment]
Interesting. I would submit this to Sketch app team, thanks.

**Comment by timuric** [comment]
@lmargo @exterry does Sketch 4.2 solves the issue?

**Comment by exterry** [comment]
@timuric @lmargo Yes just upgrade to v3.4.2 and now looks good.
Thanks @timuric

**Comment by bomberstudios** [comment]
This might be related to a bug we just fixed in Sketch, but I need more information from you guys to confirm it : )

Namely:

- do you have multiple documents open?
- if yes, can you check if the Plugin is affecting a background document? If you have anything selected, the plugin will work as expected (but in the wrong document). If you have nothing selected in the background document, the Plugin will show a warning in the background document and if you miss that it may look like it's not working at all.

Thanks in advance for your feedback : )

**Comment by AndreaBlick** [comment]
Hi, we are experiencing the same issue. Often have multiple docs open however, so will test as per the above recommendation from bomberstudios.

**Comment by lmargo** [comment]
Hi there @bomberstudios, I usually have multiple documents open so I'm not sure if this is something that happens all the time. Today I tried it out with the latest plugin, Sketch 3.4.2 and multiple docs.

The first time I tried the text generator, it didn't show up in the first document but it shows up in the second/third document open.

Next I tried closing all documents except for the one I'm working on, and ran the plugin again. The plugin didn't generate anything. 

After that I closed and reopened anything, and the plugin still didn't generate anything.

After restarting Sketch sometimes the plugin works, but it's a bit hit and miss.

Thank you all so much for all the help with this issue :) This plugin is super helpful and our team hopes we can use it again soon.

**Comment by mamezito** [comment]
when running plugin nothing happens with one document opened at sketch 3.4.2 (

**Comment by alvaroner** [comment]
I had the same issue. It worked well when I closed the others documents.

**Comment by mamezito** [comment]
thanx for hint, working

**Comment by designerandres** [comment]
For reference, this bug seems to be affecting other plugins as well after the 3.4.1 update. In my case, the Alignto plugin has the same issues.

**Comment by bomberstudios** [comment]
This issue should be fixed in 3.4.3
