### ISSUE TITLE
Plugin will only does text replacement in the first sketch window

### ISSUE THREAD

**Issue by cheics** [timuric/Content-generator-sketch-plugin#82]
Sketch Version 3.4.2 (15857)

To reproduce:
* Open a new document in Sketch (Untitled)
* Create another new document in Sketch (Untitled 2)
* Observe that both Untitled and Untitled 2 are available from TitleBar > Window
* In Untitled 2, create a rectangle and some text
* Get a placeholder image for the rectangle by selecting Plugins > Content Generator Sketch Plugin > Persona > Photos > Male
* Observe that the image is replaced correctly
* Select the text in Untitled 2 and try to get a placeholder name through Plugins > Content Generator Sketch Plugin > Persona > Names > Male
* **BUG** Notice that nothing happens...

Text replacement actions performed in the window "Untitled" will succeed. 
Text replacement actions performed n the window "Untitled 2" will succeed if it is the only (or first) window open.

Expected:
* Actions are always performed on the **Active** sketch window

**Comment by cheics** [comment]
Still no output when selecting system.log in Console.app.

**Comment by bomberstudios** [comment]
Again, should be fixed in 3.4.3
