### ISSUE TITLE
Plugin will work in another Sketch window.

### ISSUE THREAD

**Issue by bmoondesign** [timuric/Content-generator-sketch-plugin#83]
Sketch Version 3.4.2

I have two sketch windows open and when I use the plugin in one window, it seems to be applying to a layer selected in another window.

Works sometimes when I only have one window open.

**Comment by timuric** [comment]
@bmoondesign do you experience the same behavior in 3.4.3 (beta) ?

**Comment by wtrsld** [comment]
Seeing the same issue in 3.4.2, not into upgrading to the beta but if you say it's fixed there then I trust ya :)

**Comment by bomberstudios** [comment]
This should be fixed in 3.4.3, so you can probably close this one
