### ISSUE TITLE
Installation on Sketch 3.4.2

### ISSUE THREAD

**Issue by shanecarmody** [timuric/Content-generator-sketch-plugin#84]
Hi,

I think the `README.md` needs to be updated with installation instructions as I can’t install with the current ones. The following line causes the issue:

> 2. In Sketch app `Plugins > Reveal Plugins folder...`

There is no option to `Reveal Plugins folder…` in 3.4.2. Can we update the `README.md` with new instructions on how to install? For now, I don’t know what to do.

Thanks for making the plugin in any case :+1:

**Comment by pkvdesigns** [comment]
Thats right, Sketch has changed, see the video for a quick how to: http://quick.as/qax4hB462

**Comment by shanecarmody** [comment]
@pkvdesigns :+1:

**Comment by shanecarmody** [comment]
Closed via #85
