### ISSUE TITLE
Images › Flickr Keywords crashes when using 3 or more keywords

### ISSUE THREAD

**Issue by bomberstudios** [timuric/Content-generator-sketch-plugin#88]
When using 3 or more keywords for the Flickr Keyword command, Sketch crashes immediately.

I'm investigating the issue on our side, but I thought I'd mention it so you're aware of it : )

**Comment by timuric** [comment]
@bomberstudios Thanks!

**Comment by bomberstudios** [comment]
Console.app output:

```
11/12/15 16:01:44,311 Sketch[59466]: Ignoring autorelease call on <NSTextField: 0x7fb9e59c8fa0>
11/12/15 16:01:46,374 Flickr Keywords (Sketch Plugin)[59466]: icon,vector, computer
11/12/15 16:01:46,375 Sketch[59466]: -[NSError init] called; this results in an invalid NSError instance. It will raise an exception in a future release. Please call errorWithDomain:code:userInfo: or initWithDomain:code:userInfo:. This message shown only once.
11/12/15 16:01:46,377 Sketch[59466]: Exception: SyntaxError: JSON Parse error: Unexpected EOF
11/12/15 16:01:46,378 Flickr Keywords (Sketch Plugin)[59466]: SyntaxError: JSON Parse error: Unexpected EOF
line: 47
sourceURL: /Users/ale/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Content Generator Sketch Plugin/Images/Flickr Keywords.sketchplugin
column: 26
```

**Comment by bomberstudios** [comment]
Ah, you have an error in https://github.com/timuric/Content-generator-sketch-plugin/blob/master/Images/Flickr%20Keywords.sketchplugin#L22

Your regex is only replacing the first space, so if you do "foo, bar, baz" you'll get "foo,bar, baz" (instead of the expected "foo,bar,baz")

You should use `tag.replace(/\s/g, "");` (just tested, and it works fine here with that change : )

Will make a pull request in a minute
