### ISSUE TITLE
Images won't work on 3.5 (25229)

### ISSUE THREAD

**Issue by asmetanka** [timuric/Content-generator-sketch-plugin#94]
Blank shapes after try to filling

**Comment by timuric** [comment]
@asmetanka works for me in recent Beta Version 3.5 (25229)
Can you please provide more details?

**Comment by stolinski** [comment]
I'm running 25229 as well and everything works except for images. Persona images specifically do not come in at all, although persona names do.

**Comment by asmetanka** [comment]
Oh yes, just images won't work.

**Comment by sallard** [comment]
Persona images don't show up on 3.5 25232 as well. Argh!

**Comment by timuric** [comment]
Thanks for the reports. I am on it!

**Comment by miguelsmarcos** [comment]
Hi! I was able to solve this issue by replacing the line
```javascript
[fill setPatternImage:image collection:coll]
```
with the following two lines:

```javascript
layer.style().fills().firstObject().setPatternImage( image );
layer.style().fills().firstObject().setPatternFillType(1);
```
in js/**loadImage.js**

Hope that helps! Cheers

**Comment by timuric** [comment]
It's fixed now. Please update the plugin

**Comment by ralts00** [comment]
Thanks, thanks, thanks :D +1:

**Comment by timuric** [comment]
@miguelsmarcos Forgot to thank you for the tip! It worked thanks!
