### ISSUE TITLE
Content generator doesn't work with Sketch 3.5

### ISSUE THREAD

**Issue by zozomoey** [timuric/Content-generator-sketch-plugin#95]
The plugin seems to stop working once I installed the new update.

**Comment by psjak** [comment]
not working properly for me either, just replaces shapes with empty/transparent images.

**Comment by egofaylona** [comment]
Same here.

**Comment by ramijames** [comment]
Yup, images are broken for me after upgrading to 3.5

**Comment by mischugo** [comment]
Yep, for me too, only one rectangle of 24 has an effect, but does not show any image

**Comment by timuric** [comment]
Do you use updated version of the plugin from yesterday?

**Comment by HenryCh** [comment]
Hey guys,

So after Sketch update we tried to uninstall and reinstall the plugin via Sketch-toolbox. Did not work properly. But we downloaded the last version from gitHub, copied it into plugin folder and everything is working just fine now. 

Thanks.

**Comment by timuric** [comment]
Perhaps that is an issue with Sketch-toolbox

**Comment by HenryCh** [comment]
Very possible. Cause your last version is definitely working on 3.5 and it makes me more than happy :D

**Comment by mischugo** [comment]
Great! Works after manual installation rather then with toolbox
Thanks a lot!
